name: GitHub Pages Action
on:
  push:
    branches:
      - master
jobs:
  gh-pages:
    name: GitHub Pages
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-versions: 12
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        run: npm run deploy:gh-pages
