name: ESLint Action
on: [pull_request]
jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-versions: 12
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
